characters: ["A", "I", "E", "U", "O"]

# dataset
data_dir: "./data/images"
batch_size: 256
image_size: [76, 76]

# training params
classifier_training_epochs: 1
generator_training_epochs: 1
optimizer_type: Adam
optimizer_config:
  learning_rate: 0.001
classification_loss_fn: CategoricalCrossentropy
classification_loss_config:
  from_logits: True
classification_val_metric: CategoricalAccuracy
reconstruction_loss_fn: BinaryCrossentropy
reconstruction_loss_config:
  from_logits: False

checkpoint_interval: 1200 # 20 minutes
checkpoint_dir: "./checkpoints"