characters:
- "A"
- "I"
- "U"
- "E"
- "O"
- "KA"
- "KI"
- "KU"
- "KE"
- "KO"
- "SA"
- "SI"
- "SU"
- "SE"
- "SO"
- "TA"
- "TI"
- "TU"
- "TE"
- "TO"
- "NA"
- "NI"
- "NU"
- "NE"
- "NO"
- "HA"
- "HI"
- "HU"
- "HE"
- "HO"
- "MA"
- "MI"
- "MU"
- "ME"
- "MO"
- "YA"
- "YU"
- "YO"
- "RA"
- "RI"
- "RU"
- "RE"
- "RO"
- "WA"
- "WO"
- "N"

# dataset
data_dir: "./data/images"
batch_size: 32
image_size: [76, 76]

# training params
classifier_training_epochs: 20
generator_training_epochs: 20
optimizer_config:
  learning_rate: 0.001
classification_loss_fn: CategoricalCrossentropy
classification_loss_config:
  from_logits: True
classification_val_metric: CategoricalAccuracy
reconstruction_loss_fn: MeanSquaredError
reconstruction_loss_config: {}
reconstruction_loss_coef: 10

checkpoint_interval: 1200 # 20 minutes
checkpoint_dir: "./checkpoints"

classifier_save_path: ./saved_models/classifiers
generator_save_path: ./saved_models/generators
mapping_save_path: ./saved_models/mappings

predictions_output_folder: ./predictions_outputs/