characters:
- "A"
- "I"
- "U"
- "E"
- "O"
- "KA"
- "KI"
- "KU"
- "KE"
- "KO"
- "SA"
- "SI"
- "SU"
- "SE"
- "SO"
- "TA"
- "TI"
- "TU"
- "TE"
- "TO"
- "NA"
- "NI"
- "NU"
- "NE"
- "NO"
- "HA"
- "HI"
- "HU"
- "HE"
- "HO"
- "MA"
- "MI"
- "MU"
- "ME"
- "MO"
- "YA"
- "YU"
- "YO"
- "RA"
- "RI"
- "RU"
- "RE"
- "RO"
- "WA"
- "WO"
- "N"

# dataset
data_dir: "./data/images"
batch_size: 16
image_size: [76, 72]
cropped_image_size: [52, 36]

# training params
embedding_dim: 24
n_routings: 3
classifier_training_epochs: 50
generator_training_epochs: 50
optimizer_config:
  learning_rate: 0.001
classification_loss_fn: CategoricalCrossentropy
classification_loss_config:
  from_logits: True
classification_val_metric: CategoricalAccuracy
reconstruction_loss_fn: MeanSquaredError
reconstruction_loss_config: {}
reconstruction_loss_coef: 10
reduce_lr_epochs_since_improvement: 2
early_stopping_epochs_since_improvement: 3

checkpoint_interval: 1200 # 20 minutes
checkpoint_dir: "./checkpoints"

classifier_save_path: ./saved_models/classifiers
generator_save_path: ./saved_models/generators
mapping_save_path: ./saved_models/mappings
config_save_path: ./saved_models/config

predictions_output_folder: ./predictions_outputs/